media:
  input: static/posts
  output: /posts

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: content/posts
    view:
      fields: [title, date, draft, description, tags]

    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: draft
        label: Draft
        type: boolean
        default: true

      - name: description
        label: Description
        type: text
        required: true
    
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          creatable: true
          values: [Film, Review, Music, Politics, History, Fiction, Essay]
        required: true

      - name: body
        label: Content
        type: rich-text